name: catpic
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # network
  html: ^0.15.0
  xml: ^5.0.2
  brotli: ^0.5.0
  dio: ^4.0.0
  dio_cache_interceptor: ^2.2.0

  # ui
  flutter_svg: ^0.22.0
  extended_image: ^4.0.1
  sliding_sheet: ^0.5.0
  waterfall_flow: ^3.0.1
  flutter_slidable: ^0.6.0
  material_floating_search_bar: ^0.3.4
  bot_toast: ^4.0.1
  flutter_hooks: ^0.16.0
  flutter_speed_dial: ^3.0.5
  flutter_rating_bar: ^4.0.0
  video_player: ^2.1.1
  pull_to_refresh: 2.0.0
  url_launcher: ^6.0.3

  # database
  sp_util: ^2.0.3
  shared_preferences: ^2.0.5
  moor: ^4.2.1
  sqlite3_flutter_libs: ^0.4.1
  path_provider: ^2.0.1
  path: ^1.8.0

  # provider
  get: ^4.1.4
  flutter_mobx: ^2.0.0
  event_bus: ^2.0.0

  # others
  uuid: ^3.0.4
  intl: ^0.17.0
  tuple: ^2.0.0
  synchronized: ^3.0.0
  crypto: ^3.0.1
  vibration: ^1.7.4-nullsafety.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.1+3
  moor_generator: 4.2.1



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
    - assets/imgs/