name: catpic
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^3.0.10
  html: ^0.14.0+4
  flutter_mobx: ^1.1.0+2
  floor: ^0.14.0
  flutter_slidable: ^0.5.7
  intl: ^0.16.1
  bot_toast: ^3.0.5
  event_bus: ^1.1.1
  shared_preferences: ^0.5.12+4
  xml2json: ^4.4.0
  material_floating_search_bar: ^0.2.6
  waterfall_flow: ^2.0.5
  pull_to_refresh: ^1.6.3
  flutter_cache_manager: ^2.1.1
  get: ^3.24.0
  flutter_svg: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  mobx_codegen: ^1.1.2
  floor_generator: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/


flutter_intl:
  enabled: true