name: catpic
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bot_toast: ^4.0.1
  dio: ^4.0.0-prev3
  event_bus: ^2.0.0
  extended_image: ^4.0.1
  flutter_cache_manager: ^3.0.0
  flutter_mobx: ^2.0.0-nullsafety.3
  flutter_slidable: ^0.6.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  html: ^0.15.0
  shared_preferences: ^2.0.5
  sliding_sheet: ^0.5.0
  sp_util: ^2.0.3
  waterfall_flow: ^3.0.1
  intl: ^0.17.0
  xml: ^5.0.2
  brotli: ^0.5.0

  moor: ^4.2.1
  sqlite3_flutter_libs: ^0.4.1
  path_provider: ^2.0.1
  path: ^1.8.0

  material_floating_search_bar: ^0.3.4


  pull_to_refresh:
    git:
      url: https://github.com/fzyzcjy/flutter_pulltorefresh
      ref: 0bb4f70dd7540ffe032bbc2a6994df388b4f1c39

  smart_select:
    git:
      url: https://github.com/iktakahiro/flutter_smart_select.git
      ref: null-safety


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.1+2
  moor_generator: 4.2.1



flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/imgs/


flutter_intl:
  enabled: true